name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: ludeeus/action-shellcheck@2.0.0
      with: { severity: error }
      
    - name: Verify script permissions
      run: |
        echo "Checking script permissions..."
        for script in $(find . -name "*.sh" -type f | grep -v node_modules); do
          if [ ! -x "$script" ]; then
            echo "ERROR: $script is not executable"
            exit 1
          else
            echo "✓ $script is executable"
          fi
        done
